services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    volumes:
      - /self-hosted/netbootxyz/config:/config
      - /self-hosted/netbootxyz/assets:/assets #optional
    ports:
      - 3000:3000
      - 6969:69/udp
      - 8090:80 #optional
    restart: unless-stopped
